use_frameworks!

target 'RealtimeBindings_Example' do
  pod 'RealtimeBindings', :path => '../'

  target 'RealtimeBindings_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
